integr8ly/cloud-resource-operator

- .github/CODEOWNERS
- pkg/resources/config_test.go
Co-authored-by: dimitraz <dzuccare@redhat.com>
- Run `make test/unit`
> Add test for reconcile time func

- .travis.yml
- Makefile
add colours to `make test/unit`
- run `make test/unit`
should see something like
> add colours to make test/unit

- Makefile
- deploy/operator.yaml
- go.sum
- pkg/providers/openshift/provider_postgres.go
- test/e2e/cro_test.go
- test/e2e/main_test.go
Jira: https://issues.jboss.org/browse/INTLY-3773
- oc logged into a cluster
- operator-sdk version: v0.10.0
- Run `make image/build`
- Run `make image/push IMAGE_ORG=<your quay>`
- Update `deploy/operator.yaml` `image` to point to your image
- Run `make test/e2e`
> [WIP] INTLY-3773 - e2e testing

- .github/CODEOWNERS
- OWNERS
This change adds `OWNER` file and setups e2e tests to be run with PROW
> Adding owners file

- pkg/resources/util.go
- pkg/resources/util_test.go
Create utility functions in to easily deploy various custom resources. 
Jira: https://issues.jboss.org/browse/INTLY-3870
To do
> [WIP] Add utility functions for custom resource creation

- README.md
- deploy/crds/integreatly_v1alpha1_blobstorage_cr.yaml
- deploy/crds/integreatly_v1alpha1_postgres_cr.yaml
- deploy/crds/integreatly_v1alpha1_redis_cr.yaml
- deploy/crds/integreatly_v1alpha1_smtpcredentialset_cr.yaml
- deploy/examples/cloud_resources_aws_strategies.yaml
- doc/blobstorage.md
Update the readme to include steps on how to manually peer two VPCs
> add vpc peering connection steps

- Makefile
Add setup make command for prow e2e
> add prow e2e setup

- .travis.yml
ensure travis is logged into quay before attempting to do a push
> travis tag stage fix

- Makefile
Removes `sudo` from operator-sdk setup
> update prow setup command

- Makefile
> update prow setup and test target

- Makefile
/assign aidenkeating
/assign mikenairn
> add go module on to prow e2e

- README.md
ensure the vpc peering steps mentions the security group updates required
> update vpc peering docs for security groups

- pkg/providers/config.go
> set defaults to openshift

- pkg/providers/openshift/config.go
> provide production defaults for openshift

- Makefile
- deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
- deploy/olm-catalog/cloud-resources/cloud-resource-operator.package.yaml
- version/version.go
@dimitraz I think we'll be good to create a tag after this, mind taking a look?
> bump version to 0.2.0

- Makefile
- deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
- deploy/olm-catalog/cloud-resources/cloud-resource-operator.package.yaml
- pkg/providers/openshift/provider_postgres.go
- pkg/providers/openshift/provider_redis.go
- version/version.go
Bump the operator version to 0.3.0
> bump version to 0.3.0

- pkg/providers/openshift/provider_postgres.go
- pkg/providers/openshift/provider_redis.go
Fixes a bug in the openshift deletion logic, where resources would only get cleaned up when deployments were in an `available` state. 
- Update the cluster service version for the `cloud-resources` manifest in the integreatly repo to point to my quay.io: `quay.io/dimitra/cloud-resource-operator:fix-oc` 
- Run the operator locally (at least 3scale and codeready)
```
make cluster/prepare/local
make code/run/service_account 
```
- Once the products have successfully completed, delete the installation and ensure that all the cro resources are deleted
> refactor openshift deletion

- pkg/providers/openshift/provider_redis.go
> refactor redis openshift deletion

- README.md
Jira: N/A
The following changes adds more details to the current VPC peering documentation located in the README.
- Follow the process stated in the documentation and ensure that VPC peering works successefully
> add more details to the vpc peering documentation

- Makefile
- deploy/role_binding.yaml
Jira: https://issues.redhat.com/browse/INTLY-4503
- Seed the cluster with some resources 
- Run `make code/run/service_account`
- Ensure the operator behaves as expected
> add new run service account target

- go.mod
- go.sum
- pkg/controller/blobstorage/blobstorage_controller.go
- pkg/controller/postgres/postgres_controller.go
- pkg/controller/redis/redis_controller.go
- pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
- pkg/providers/aws/provider_blobstorage.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_smtpcredentialset.go
- pkg/providers/openshift/provider_blobstorage.go
- pkg/providers/openshift/provider_postgres.go
- pkg/providers/openshift/provider_redis.go
- pkg/providers/openshift/provider_smtpcredentialset.go
- pkg/providers/types.go
- pkg/resources/phase.go
- pkg/resources/provider.go
- pkg/resources/util.go
Jira: https://issues.redhat.com/browse/INTLY-3779
*Note* : Included in this change, is some technical debt, updating and formatting import alias `croType`
- Seed the cluster with both redis and postgres
- Delete both CR's while they are creating
- Ensure the status message reflects the current status of the resource and the current phase it is in
> Add delete status

- pkg/providers/aws/provider_redis.go
Fixed confusing log in redis provider
Jira: https://issues.redhat.com/browse/INTLY-4906
> Fixed redis log message

- README.md
- pkg/providers/aws/config.go
- pkg/providers/aws/provider_blobstorage.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_redis.go
- pkg/resources/cluster.go
- Run operator and ensure runs correctly
> fixed linting errors in ClusterId

- pkg/providers/config.go
- pkg/providers/types.go
- pkg/resources/finalizers.go
- pkg/resources/phase.go
- pkg/resources/strings.go
Added some comments to remove linting warning. Remaining lint warnings are for uncommented, but self explanatory code
- Ensure...
> Added some comments

- pkg/providers/aws/credentials.go
- pkg/providers/aws/credentials_moq.go
- pkg/providers/aws/provider_blobstorage.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_redis_test.go
- pkg/providers/aws/provider_smtpcredentialset_test.go
- pkg/providers/openshift/provider_postgres.go
- pkg/providers/openshift/provider_postgres_test.go
- pkg/providers/openshift/provider_redis.go
- pkg/providers/openshift/provider_redis_test.go
Renamed providers to remove 'stuttering' linting error
- Ensure...
> Intly 4941 remove stuttering

- pkg/apis/integreatly/v1alpha1/smtpcredentialset_types.go
- pkg/controller/blobstorage/blobstorage_controller.go
- pkg/controller/postgres/postgres_controller.go
- pkg/controller/redis/redis_controller.go
- pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
- pkg/providers/aws/config.go
- pkg/providers/aws/credentials.go
- pkg/providers/aws/provider_blobstorage.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_redis_test.go
- pkg/providers/aws/provider_smtpcredentialset.go
- pkg/providers/config.go
- pkg/providers/openshift/config.go
- pkg/providers/types.go
- pkg/resources/config.go
- pkg/resources/custom_metrics.go
- pkg/resources/strings.go
Fixed comment syntax to remove linting errors
- Ensure...
> fixed comment syntax

- pkg/providers/aws/credentials.go
- pkg/providers/aws/provider_blobstorage.go
- pkg/providers/aws/provider_blobstorage_test.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_redis.go
this includes:
- rds
- elasticache
- s3
see commit messages for more details:
- 884ddf8
- 96986ef
- fd5fe75
verification:
- additional to commit message verification
- ensure an rhmi installation completes using the
changes provided in this pr
- ensure backup jobs and threescale cms logic works
with the changes provided in this pr
> ensure privacy settings are set correctly for each resource that the cloud resource operator provides via aws

- pkg/providers/aws/credentials.go
Jira: https://issues.redhat.com/browse/INTLY-7223
> add cloudwatch premissions to credentials minter

- pkg/providers/aws/credentials.go
Updated AWS cloudwatch permission request from GetMetricStatistics to GetMetricData
> updated aws cloudwatch function

- pkg/providers/aws/cluster_vpc.go
- pkg/providers/aws/provider_postgres_test.go
@maleck13 2333b52 is the actual documentation commit
> Cluster VPC documentation

- Update_CRO_rhmi.md
readme for steps for updating cro on rhmi. quite a few manual steps should have them written down.
> add readme Update_CRO_rhmi.md

- pkg/providers/aws/provider_postgres.go
Based on comment in [this PR](https://github.com/integr8ly/cluster-service/pull/12#issuecomment-642559165)
> fix: RDS subnet group tag

- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_redis.go
Jira: https://issues.redhat.com/browse/INTLY-9490
- Create a postgres CR
- once the Postgres is fully created, go to the metrics endpoint of CRO
* you should see that the `cro_postgres_available` metric is set to `1` because the instance is available
* you should see that there is an additional `status` label on the metric that reports a value that came back from AWS like `available`
- Go to AWS and make a modification to the RDS instance, for example: change the storage size. This will cause the instance to go into a modifying state.
- Check the metrics exposed by CRO and notice the `status` label should change to `modifying` but the value should still stay `1`. This means the metric is still reporting the postgres as …
> fix: tweak availability metrics for redis and postgres

- .github/pull_request_template.md
- hack/aws/README.md
- hack/aws/supported_types.sh
Jira: https://issues.redhat.com/browse/INTLY-9737
- run `./supported_types.sh t3.micro `
> aws supported types script 

- OWNERS
they have taken the oath.
in brightest day, in blackest night,
no evil shall escape my sight.
let those who worship evil's might,
beware my power - cloud resource operator's light!
we must grant them the power.
> grant unlimited power

- hack/postgres/README.md
- hack/postgres/clean.sh
- hack/postgres/cpuUtil.sh
Co-authored-by: Laura Fitzgerald <lfitzger@redhat.com>
Jira: https://issues.redhat.com/browse/INTLY-7232
Follow the steps added to the readme and verify that the cpuUtil raises to >90%
> added script for forcing postgres cpu util above 90%

- Makefile
https://issues.redhat.com/browse/INTLY-9497
- Change something in the code base that should be fixed by `gofmt` (e.g manually indent a first line of code) and save
- Run `make code/check`
- You should see a report about the formatting issue
- Run `echo $?`
- Return code of the command should be non-zero
> fix: fail on code format check

- pkg/providers/aws/credentials.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/resources/custom_metrics.go
Jira: https://issues.redhat.com/browse/INTLY-7233
- Ensure...
> expose postgres max memory metric, add postgres load testing scripts

- hack/postgres/README.md
- hack/postgres/memUsageExec.sh
used to verify https://github.com/integr8ly/integreatly-operator/pull/1159
- Ensure...
> fix: add script for lowering postgres memory

- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/INTLY-10247
- Create a Postgres CR and ensure AutoMinorVersionUpgrade is set to false by default
`aws rds describe-db-instances | grep AutoMinorVersionUpgrade`
> set AutoMinorVersionUpgrade to false by default

- cmd/manager/main.go
- internal/k8sutil/k8sutil.go
- pkg/providers/aws/cluster_network_provider.go
- pkg/providers/aws/config.go
- pkg/providers/aws/config_test.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/config.go
- pkg/providers/openshift/config.go
- pkg/providers/openshift/config_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-1029
This PR does not include a new feature. Verify that CRO still works as expected.
1. Build an image of the operator
2. In a cluster, install RHOAM, replacing the CRO image for the custom one in the manifest
3. Verify that the installation successfully completes
> MGDAPI-1029: Remove dependency to k8sutil package

- Dockerfile
- build/Dockerfile
> bump ubi version to 8

- pkg/client/util.go
- pkg/client/util_test.go
> update client postgres reconcile function

- OWNERS
> remove oleg, add MStokluska as approver

- Update_CRO_integreatly-operator.md
> MGDAPI-3095 update the readme

- OWNERS
> MGDAPI-* add briangallagher to the approvers and reviewers

- OWNERS
Add all rhoam dev team as reviewers for CRO
> MGDAPI-3225 Add all rhoam dev team as reviewers for CRO

- Makefile
- packagemanifests/0.33.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- packagemanifests/0.33.0/cloud-resource-operator.clusterserviceversion.yaml
- packagemanifests/0.33.0/integreatly.org_blobstorages.yaml
- packagemanifests/0.33.0/integreatly.org_postgres.yaml
- packagemanifests/0.33.0/integreatly.org_postgressnapshots.yaml
- packagemanifests/0.33.0/integreatly.org_redis.yaml
- packagemanifests/0.33.0/integreatly.org_redissnapshots.yaml
- packagemanifests/0.33.0/operator-metrics-service_v1_service.yaml
- packagemanifests/cloud-resource-operator.package.yaml
- pkg/providers/aws/cluster_network_provider_test.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_redis_test.go
- pkg/resources/custom_metrics.go
- version/version.go
Jira: [MGDAPI-3234](https://issues.redhat.com/browse/MGDAPI-3234)
- Scan the code for issue
- Running of unit tests sufficient
> fix snapshot not found issues and bump cro

- pkg/providers/aws/provider_redis.go
- pkg/resources/custom_metrics.go
> fix metrics

- README.md
Jira: [MGDAPI-3228](https://issues.redhat.com/browse/MGDAPI-3228)
Added instructions for deploy and upgrade scenarios for CRO through OLM.
> MGDAPI-3228 - update CRO readme

- hack/codecov.sh
* MGDAPI-2683
* a follow-up on https://github.com/integr8ly/cloud-resource-operator/pull/302
> MGDAPI-2683 fix condition

- controllers/postgressnapshot/postgressnapshot_controller.go
- controllers/redissnapshot/redissnapshot_controller.go
- pkg/providers/aws/config_test.go
- pkg/providers/aws/credentials.go
- pkg/providers/aws/credentials_sts_manager.go
- pkg/providers/aws/credentials_test.go
- scripts/sts/create-rosa-sts.sh
Jira: https://issues.redhat.com/browse/MGDAPI-1716
Finished the work from the original PR (#216). It involved addressing feedback and adding unit tests.
- Run the unit tests with coverage for the aws provider package (`pkg/providers/aws`). It can be done by right clicking the package and selecting `Run with coverage`.
> [MGDAPI-1716] fix: address feedback from #216

- .gitignore
- scripts/sts/create-rhoam-policy.sh
JIRA: https://issues.redhat.com/browse/MGDAPI-1719
Minimal policy documentation: https://docs.google.com/document/d/1iAYApTAReEGuT8pXBRIPBCGD7WiGJrrfXqEEvDQBjzQ/edit#
> [MGDAPI-1719] replace managed admin policy with minimal policy for sts usage

- Update_CRO_integreatly-operator.md
Jira: MGDAPI-3552
Release Readme update
> MGDAPI-3552 update release doc

- .codecov.yml
Jira: [MGDAPI-3745](https://issues.redhat.com/browse/MGDAPI-3745)
> MGDAPI-3745 / Added threshold and ignore

- scripts/sts/create-rhoam-policy.sh
Jira: https://issues.redhat.com/browse/MGDAPI-3782
* Run `make setup/sts` 
* Verify `rh-oidc-staging.s3.us-east-1.amazonaws.com` is used by default in the role
* Run `OCM_ENV=production make setup/sts`
* Verify `rh-oidc.s3.us-east-1.amazonaws.com/` is used by the role
> MGDAPI-3782 - refactor: support staging oidc url

- OWNERS
> add slav as reviewer

- .codecov.yml
- pkg/providers/aws/cluster_network_provider.go
- pkg/providers/aws/cluster_network_provider_test.go
- pkg/providers/aws/cluster_vpc.go
- pkg/providers/aws/cluster_vpc_test.go
- pkg/providers/aws/config.go
- pkg/providers/aws/config_test.go
- pkg/providers/aws/connection_tester_test.go
- pkg/providers/aws/credentials.go
- pkg/providers/aws/credentials_sts_manager.go
- pkg/providers/aws/credentials_sts_manager_test.go
- pkg/providers/aws/credentials_test.go
- pkg/providers/aws/provider_blobstorage_test.go
- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/providers/aws/provider_postgressnapshot_test.go
- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_redis_test.go
- pkg/providers/aws/provider_redissnapshot_test.go
- pkg/providers/aws/tags.go
- pkg/providers/aws/tags_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-3942
- Check that code coverage is satisfactory and that the changes make sense
> [MGDAPI-3942] improve code coverage on the STS feature branch

- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
Jira: [https://issues.redhat.com/browse/MGDAPI-4115](https://issues.redhat.com/browse/MGDAPI-4115)
- Remove the added code `pmac.AutoAppliedAfterDate != nil check 
- Run the test. it will fail on the line 1282 with nil dereference
- Add the line back in a re run the test, it will pass
> check for nil AutoAppliedAfterDate on pending maintenance action

- Makefile
Jira: [MGDAPI-4309](https://issues.redhat.com/browse/MGDAPI-4309)
- Ensure you have oc cli 4.11 locally
- Ensure reconciliation begins
> MGDAPI-4309 provide token support for osd 4.11 clusters

- config/manager/manager.yaml
- main.go
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Adds health and ready checks for the CRO `manager`.
Jira: [MGDAPI-3288](https://issues.redhat.com/browse/MGDAPI-3288)
> Added health check for CRO manager setup

- pkg/client/aws/strategies_aws.go
- pkg/client/aws/strategies_aws_test.go
- pkg/client/gcp/strategies_gcp.go
- pkg/client/strategies.go
- pkg/client/strategies_test.go
- pkg/client/types/types.go
- pkg/client/util_test.go
- pkg/providers/gcp/gcpiface/database_types.go
- pkg/providers/gcp/gcpiface/database_types_test.go
- pkg/providers/gcp/gcpiface/sqladmin_api.go
- pkg/providers/gcp/provider_postgres.go
- pkg/providers/gcp/provider_postgres_test.go
- pkg/resources/cluster.go
[MGDAPI-5081](https://issues.redhat.com/browse/MGDAPI-5081)
- Modified the strategy client code for use with both AWS and GCP cloud providers
- Made some modifications to the postgres configuration to avoid a nil pointer and to set up the network configuration to use private network
Verify alongside related RHOAM PR integr8ly/integreatly-operator#3100 - this CRO PR should be merged first!
> MGDAPI-5081 - Updates to CRO GCP for RHOAM

- pkg/providers/aws/provider_redis.go
- pkg/providers/aws/provider_redis_test.go
Jira: [MGDAPI-4172](https://issues.redhat.com/browse/MGDAPI-4172)
- checkout this pr
```
gh pr checkout 668
```
- run unit tests and ensure they pass
```
make test/unit
```
- review code
> MGDAPI-4172 cover nil parameters in redis security updates

- pkg/providers/gcp/provider_postgres.go
- pkg/providers/gcp/provider_redis.go
Jira: [MGDAPI-5220](https://issues.redhat.com/browse/MGDAPI-5220)
Adding postgres and redis versions to CRs. This is related to this [PR](https://github.com/integr8ly/integreatly-operator/pull/3117) for integreatly operator.
Eye review of code should be sufficient.
> MGDAPI-5220 adding postgres and redis versions to CRs

- pkg/providers/aws/provider_postgres.go
- pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-5512
- Code review is likely fine
If you want to verify metric:
- Provision or borrow AWS CCS cluster
- Run `PROVIDER=aws make cluster/seed/postgres`
- Ensure
- Postgres provisions successfully
- Metric is converted to bytes
```
curl localhost:8383/metrics | grep cro_postgres_max_memory
```
> MGDAPI-5512 - feat: use bytes as cro postgres max memory metric

- OWNERS
> MGDAPI-99999-addcarlowner

- .golangci.yaml
- pkg/client/util_test.go
- pkg/providers/aws/cluster_vpc.go
- pkg/providers/aws/cluster_vpc_test.go
- pkg/providers/aws/config.go
- pkg/providers/aws/credentials.go
- pkg/providers/aws/credentials_sts_manager.go
- pkg/providers/aws/provider_blobstorage_test.go
- pkg/providers/aws/provider_postgres_test.go
- pkg/providers/aws/provider_redis_test.go
- pkg/providers/config.go
- pkg/providers/gcp/provider_postgres.go
- pkg/providers/gcp/provider_postgres_test.go
- pkg/providers/openshift/config.go
- pkg/providers/openshift/provider_redis_test.go
- pkg/providers/types.go
- pkg/resources/finalizers.go
- pkg/resources/phase.go
- pkg/resources/strings.go
- pkg/resources/version_test.go
Errors addressed for staticcheck linters  SA4006, SA9003 & SA1019
Jiras: 
[https://issues.redhat.com/browse/MGDAPI-5828](url)
[https://issues.redhat.com/browse/MGDAPI-5829](url)
[https://issues.redhat.com/browse/MGDAPI-5830](url)
- Run `make test/lint`
- Confirm there are no errors in the output
- Code review
> MGDAPI-5828/5829/5830 linter issues addressed with golangci

- openshift-ci/Dockerfile.tools
Jira: MGDAPI-6061 
prow checks pass
> MGDAPI-6061 change openshift-ci to go1.19

- .gitignore
- Dockerfile
- Makefile
- build/Dockerfile
- go.mod
- openshift-ci/Dockerfile.tools
> MGDAPI-6379 testing 1.20 issues

- Makefile
- scripts/create-olm-bundle.sh
- scripts/imageExists.sh
Jira: https://issues.redhat.com/browse/MGDAPI-6421
Note: for podman, this will only work together with https://github.com/integr8ly/cloud-resource-operator/pull/827
- Clone this repo, add changes from #827 on top
- Have either podman or docker installed
- export CONTAINER_ENGINE=<docker or podman> # ideally to try with both
- define other required env vars and execute the scripts / make targets that has been changed in this PR
Alternatively, use this pipeline:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Playground/job/trepel/job/cro-release/
Or just go through this successful build logs
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Playground/job/trepel/job/cro-release/17/
- this one is with docker …
> MGDAPI-6421 Make container engine configurable

- scripts/imageExists.sh
Jira:  https://issues.redhat.com/browse/MGDAPI-6423
Run script locally, simulate parameters
Script was tested locally, logs available in Task
> MGDAPI-6423 - fix imageExists.sh

- Makefile
- build/Dockerfile
- config/manager/kustomization.yaml
> MGDAPI-1234 test
