Makefile
`make cluster/clean` was not working using the wildcard
Added the full commands for removing the crd.
=> fix make cluser/clean

deploy/crds/integreatly_v1alpha1_redis_cr.yaml, pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/providers/openshift/provider_redis.go, pkg/providers/openshift/provider_redis_test.go, pkg/providers/types.go
Current the redis secret created for AWS and Openshift are different. This change formats the secrets so that they are the same
- Run `make cluster/prepare` and `make cluster/seed/redis`
- Verify the secret created is split to `uri` and `port`
=> format aws redis secret to match openshift redis secret

pkg/providers/aws/config.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_smtpcredentialset.go, pkg/providers/config.go, pkg/providers/config_test.go, pkg/providers/openshift/config.go, pkg/providers/openshift/provider_postgres.go, pkg/providers/openshift/provider_redis.go, pkg/resources/configmaps.go
currently, if the config for either the operator or each provider
cannot be found, the operator will crash with a config missing error.
this is not ideal, and with rhmi we would like to not have to
pre-create configmaps.
this solution, simply provides an entirely default configmap that
is used if the expected configmap is not found.
there is also some general cleanup around provider logging
included.
verification:
- run the operator without any config maps present
- ensure the operator doesn't crash
- attempt a deploy of a service e.g. blobstorage without any
provider config map present
- ensure it completes successfully
=> use default config when configmap cannot be found

pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/postgres/postgres_controller.go, pkg/controller/redis/redis_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
Currently we do not `Requeue on deletion`, which leads to problems when a resource is slow to be deleted. This change adds the `requeue` parameter and increased the reconcile to 30 seconds while the resource is being deleted
- Run `make cluster/seed/redis`
- Verify the elastiCache cluster is being created
- Delete the redis `example-redis` 
- Verify the log message changes, 
- Verify elastiCache deletes
=> update delete reconcile to requeue

pkg/providers/aws/provider_blobstorage.go
Currently we prefix blob storage resource with the name space. This change removes the prefix to match how we handle resource names in Redis and Postgres.
=> remove namespace prefix from blob storage name

pkg/providers/aws/provider_blobstorage.go
The naming convention on the blob storage delete function needed to be updated
=> update blob name on delete func

Makefile, deploy/examples/cloud_resources_aws_strategies.yaml, go.mod, go.sum, pkg/providers/aws/config.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, tools.go
Jira: https://issues.jboss.org/browse/INTLY-3568
This PR adds a snapshot/backup on delete of Redis 
FYI Redis takes a while to create but sometimes its worth hitting refresh aws console pages, and to create a snapshot on aws
- Run `make cluster/clean`
- Remove the CR
```sh
oc delete -f ./deploy/crds/integreatly_v1alpha1_redis_cr.yaml
```
- Apply the CR again
```sh
oc apply -f ./deploy/crds/integreatly_v1alpha1_redis_cr.yaml
```
- Edit the configmap `cloud-resources-aws-strategies` redis `deleteStrategy` , in the namespace: `kube-system`  and set the `FinalSnapshotIdentifier` to an empty string
```yaml
data:
blobstorage: |
{"development": { "region": "eu-west-1", "createStrategy": {} }}
postgres: >
{"development": { …
```
=> Add FinalSnapshotIdentifier to force snapshot on deletion

pkg/providers/aws/provider_blobstorage.go
Currently the intly operator requires to know the region. This change returns the region in the created secret
- Run `make cluster/seed/blobstorage`
- Ensure the region is returned in the secret
=> add bucket region to returned secret

pkg/providers/aws/config.go
Currently we have no `production` defaults which causes errors during development on the intly operator
=> add production defaults for aws

deploy/examples/cloud_resources_aws_strategies.yaml, pkg/providers/aws/credentials.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_blobstorage_test.go
Jira: https://issues.jboss.org/browse/INTLY-3958
- Create `BlobStorage`
- Add objects to bucket
- Delete `BlobStorage`
- The CR and Creds should be deleted and the bucket still there
- Create another `BlobStorage` 
- Dont add objects to bucket
- Delete `BlobStorage` everything should be cleaned up
- Update `forceBucketDeletion` to `true`
- Create `BlobStorage`
- Add objects to bucket
- Delete `BlobStorage`
- Everything should be deleted
=> add force delete option blob storage

deploy/crds/integreatly_v1alpha1_postgres_cr.yaml, pkg/providers/aws/config.go, pkg/providers/openshift/config.go
bug fix, remove namespace from postgres cr and set the finilizers to the same name
- Change the name space in the Makefile `integreatly-operator`
- Deploy `managed` and `workshop` by changing the postgres cr
- Run `make cluster/seed/postgres`
- make sure that the postgres cr points at `integreatly-operator`
- make sure that when the postgres cr is deleted all resources are removed .
=> remove namespace from postgres cr and set the finilizers to the same name

deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go, pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/postgres/postgres_controller.go, pkg/controller/redis/redis_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller_test.go, pkg/providers/aws/config.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_blobstorage_test.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/providers/aws/provider_smtpcredentialset.go, pkg/providers/aws/provider_smtpcredentialset_test.go, pkg/providers/openshift/config.go, pkg/providers/openshift/provider_postgres.go, pkg/providers/openshift/provider_postgres_test.go, pkg/providers/openshift/provider_redis.go, pkg/providers/openshift/provider_redis_test.go, pkg/providers/types.go, pkg/providers/types_moq.go, pkg/resources/config.go, pkg/resources/config_test.go
currently we have a global override for the reconcile timings in
each resource type. however this should be more individual instead
of allowing a controller to decide what the timings should be.
this change performs a slight refactor to the current reconcile
time override function and also ensures each provider can return
it's own reconcile time based on knowledge of the cr state.
=> add provider specified reconcile timeouts

go.sum, pkg/apis/integreatly/v1alpha1/types.go, pkg/apis/integreatly/v1alpha1/types_test.go, pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/postgres/postgres_controller.go, pkg/controller/redis/redis_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go, pkg/providers/aws/config.go, pkg/providers/aws/config_test.go, pkg/providers/config_test.go, pkg/providers/openshift/config.go, pkg/providers/openshift/config_test.go, pkg/resources/strings.go, pkg/resources/strings_test.go
currently, when there is not a provider for the type of the cr a
message is returned.
this change ensures the message returned is a standard.
currently, when an error occurs in a provider, only an overview
message is returned to the status block of the cr.
this change adds a WrapError function to act on the StatusMessage
struct that includes the returned string from the Error function
of an underlying error. This makes the status block slightly more
verbose in error situations.
currently, it is possible that the string returned from the util
string shortening function, ShortenString, is not url or aws
resource name-safe. this is due to a number of reasons that allow
for characters such as underscores due to base64 encoding or double
hyphens due to the way there was no preprocessing on the …
=> ensure unsupported provided and tiers are included in status block

deploy/examples/cloud_resource_config.yaml, deploy/examples/cloud_resource_openshift_strategies.yaml, deploy/examples/cloud_resources_aws_strategies.yaml, pkg/providers/aws/config.go, pkg/providers/aws/config_test.go, pkg/providers/config.go, pkg/providers/openshift/config.go, pkg/providers/openshift/config_test.go
Jira: https://issues.jboss.org/browse/INTLY-3896
- Run `make cluster/seed/postgres`
- Ensure that cro configmap's are created in the `cloud-resources-operator` namespace
- Change the `NAMESPACE=` var in the makefile
- Run `make cluster/seed/postgres`
- Ensure that cro configmap's are created in the new namespace
- Ensure no cro resources are created under the `kube-system` namespace
=> Change from kube-system namespace by default

Makefile, test/e2e/cro_test.go
Currently we are running e2e tests from a built image of the operator, to allow for easier CI we need to run the operator locally during testing.
- Run `make cluster/clean`
- Run `make test/e2e`
- Ensure tests pass
=> Run e2e tests with local operator

Makefile, go.mod, go.sum, pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_smtpcredentialset.go, pkg/providers/aws/provider_smtpcredentialset_test.go, pkg/providers/openshift/provider_blobstorage.go, pkg/providers/openshift/provider_blobstorage_test.go, pkg/providers/openshift/provider_smtpcredentialset.go, pkg/providers/openshift/provider_smtpcredentialset_test.go, pkg/resources/strings.go, pkg/resources/strings_test.go, test/e2e/cro_test.go, test/e2e/openshift_blobstorage_test.go, test/e2e/openshift_smtp_test.go
Currently we do support Openshift installs of blobstorage and smtp resources. This change adds the support and e2e 
- Provision smtp and blobstorage workshops
- Ensure secrets are created
- Run `make cluster/clean`
- Run `make test/e2e/local`
- Ensure tests pass
=> Openshift Basic Providers

Makefile, cmd/manager/main.go, go.mod
None
Adding monitoring-key:middleware to the service monitor created by the operator itself so the metrics can be fed into the middleware monitoring prometheus.
- Checkout this branch
- Modify `operator.yaml` image to  `quay.io/davidffrench/cloud-resource-operator:add_monitoring_label`
- Run `kubectl deploy -f deploy/operator.yaml`
- Check the service-monitor created by the operator in the same namespace has the correct `monitoring-key:middleware` label
=> feat: Add monitoring label to operator service monitor

pkg/providers/openshift/provider_postgres.go, pkg/providers/openshift/provider_postgres_test.go
Fixes secret naming clashes when multiple postgres instances are deployed in the same namespace
- Update the cluster service version for the `cloud-resources` manifest in the integreatly repo to point to my quay.io: `quay.io/dimitra/cloud-resource-operator:test` 
- Run the operator locally
```
make cluster/prepare/local
make code/run/service_account 
```
- Verify that codeready comes up successfully 
- Verify that there are 2 `<installation-name>-postgres-credentials` secrets in the integreatly namespace, 1 for 3scale and 1 for codeready
- Run cro from this branch
- Create 2 postgres instances in the same namespace
- Ensure both instances run correctly and 2 separate credential secrets are created
=> fix credentials secret name clash

README.md, deploy/crds/integreatly_v1alpha1_blobstorage_crd.yaml, deploy/crds/integreatly_v1alpha1_postgres_crd.yaml, deploy/crds/integreatly_v1alpha1_redis_crd.yaml, deploy/crds/integreatly_v1alpha1_smtpcredentialset_crd.yaml, pkg/apis/integreatly/v1alpha1/types/types.go, pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go, pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/postgres/postgres_controller.go, pkg/controller/redis/redis_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go, pkg/providers/aws/provider_redis.go
Jira: https://issues.redhat.com/browse/INTLY-4345
- Seed the cluster with the following
```
apiVersion: integreatly.org/v1alpha1
kind: Redis
metadata:
name: example-redis
spec:
secretRef:
name: example-redis-sec
tier: development
type: managed
skipCreate: true
```
```
apiVersion: integreatly.org/v1alpha1
kind: Postgres
metadata:
name: example-postgres
spec:
secretRef:
name: example-postgres-sec
tier: development
type: managed
skipCreate: true
```
- Ensure both Postgres and Redis creation has not begun in AWS and the `Status` is updated to `paused`
- Remove `skipCreate: true` from CR's or set `skipCreate:false`
- Ensure both Postgres and Redis creation starts in AWS and the `Status` changed to reflect that.
=> add skip create logic to aws redis and postgres

Makefile, deploy/crds/integreatly_v1alpha1_blobstorage_cr.yaml, deploy/crds/integreatly_v1alpha1_postgres_cr.yaml, deploy/crds/integreatly_v1alpha1_redis_cr.yaml, deploy/crds/integreatly_v1alpha1_smtpcredentialset_cr.yaml
During development we often have to switch between provisioning managed and workshop types. To help speed up this process this change allows you to seed the `type` you want
- Run make seed targets
- Ensure CR's are created as expected
=> Update seed targets

Makefile
gnu sed is not used by default on bsd/macos systems. this change
attempts to make the sed command used in the gen/csv makefile target
portable for systems which primarily are used in cloud resource
operator development.
verification:
- on macos, run gen/csv and ensure it completes
- on linux, run gen/csv and ensure it completes
=> make gen/csv makefile target portable

deploy/olm-catalog/cloud-resources/0.6.0/cloud-resources.v0.6.0.clusterserviceversion.yaml, go.mod, pkg/resources/config.go, pkg/resources/util.go, pkg/resources/util_test.go
Currently description and display name is not generated by the Operator SDK
This change adds both for the new crd`s in the csv
- Update MakeFile to target your Quay
- Run `make image/push`
- Run `make manifest/push`
- Ensure you set the Quay Application and Repo to publc
- Create a new Operator Source pointing at your Quay
```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
name: integreatly-operators
namespace: openshift-marketplace
spec:
authorizationToken: {}
displayName: Integreatly Operators
endpoint: 'https://quay.io/cnr'
publisher: Integreatly Publisher
registryNamespace: <<YOUR QUAY NAME>>
type: appregistry
```
- Create a `Cloud Resource Operator` subscription from OLM
- Ensure the subscription is a success and the operator is installed
=> Fix CSV Formatting & Add Product Name to Util Function

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
In order to make a cleaner alert we decided on returning a value of `1` to represent an `available resource` and a value of `0` to represent an `unavailable resource`
- Run `curl localhost:8383/metrics | grep aws `
- Ensure `cro_aws_rds_available` and `cro_aws_elasticache_available` metric and the value represents the current state of the provisioning resource
=> add available metrics

cmd/manager/main.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Fixed issue with creating servicemonitors in the namespace the operaor is running in
Targetting exported_namespace in metric alerts
The servicemonitor is now being created for the operator metrics service when the watch namespace is different to the namespace in which the CRO is running.
The alerts which are created for availability now correctly target `exported_namespace` rather than `namespace`
- `oc create namespace "namespace-a"`
- `oc create namespace "namespace-b"`
- Update the deployment for the CRO, change the:
```
env:
- name: WATCH_NAMESPACE
value: "namespace-b"
```
- `oc apply -f deploy/operator.yaml --namespace "namespace-a"`
- Ensure that a servicemonitor is created in the namespace where the CRO is running
=> Targetting exported_namespace in metric alerts

deploy/cluster_role.yaml, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Altered ordering for when PromtheusRules are deleted for RDS/ElastiCache resources
Jira: https://issues.redhat.com/browse/INTLY-5109
- Run `oc create namespace "namespace-a"`
- Run `oc create namespace "namespace-b"`
- Run `oc project namespace-a`
- Run `make image/build`
- Run `docker tag <image>:0.8.1 <image-with-your-name>:v0.8.1`
- Run `docker push <image-with-your-name>:v0.8.1`
- Update the image in the `deploy/operator.yaml`
- Update the deployment for the CRO, change the:
```
env:
- name: WATCH_NAMESPACE
value: "namespace-b"
```
- `oc apply -f deploy/operator.yaml --namespace "namespace-a"`
- Create a Redis/Postgresql CR in `namespace-b`
- Ensure that a ServiceMonitor is created in the `namespace-a` where the CRO is running
- Ensure …
=> Adding cluster role permissions to CRO to manage PrometheusRules

go.mod, pkg/controller/postgressnapshot/postgressnapshot_controller.go, pkg/controller/redissnapshot/redissnapshot_controller.go, pkg/providers/aws/config.go, pkg/providers/aws/config_test.go, pkg/providers/aws/credentials.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_smtpcredentialset.go, pkg/providers/aws/provider_smtpcredentialset_test.go, pkg/resources/cluster.go
currently aws regions are not being set in a way which would
benefit rhmi, instead defaulting to eu-west-1 for aws deploys.
this change sets a priority to different ways of retrieving the
aws region in aws providers:
- try from the configmap strategy 'region' key
- try from the 'cluster' infrastructure cr in openshift
- error
this results in there being no more hardcoded region in the
operator, which was used heavily during development. and ensures
that, unless explicitly overridden with a configmap, rhmi services
will attempt to be provisioned in the same region as the openshift
cluster that the operator is running in.
verification:
- run the operator against a non-eu-west-1 region cluster
- ensure services come up as expected
=> fix region reconciliation in aws service providers

go.mod, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/resources/custom_metrics.go
Jira: https://issues.redhat.com/browse/INTLY-5109
- Create a managed postgres instance and a managed redis instance:
```
make cluster/seed/managed/redis
```
- Ensure the metrics `cro_redis_available` and `cro_postgres_available` are being exposed
- Ensure that the promethus rules are getting created and 
- Ensure that alert names, descriptions, etc do not contain provider specific terminology (eg should be Postgres over RDS)
=> Refactor metric and alert names 

pkg/controller/blobstorage/blobstorage_controller.go, pkg/controller/postgres/postgres_controller.go, pkg/controller/redis/redis_controller.go, pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
Jira: https://issues.redhat.com/browse/INTLY-5447
- Run `make seed/managed/postgres`
- edit the cloud-resource-config configmap on the cluster and change the managed section to point to openshift as follows
```yaml
data:
managed: >
{"blobstorage":"aws", "smtpcredentials":"aws", "redis":"aws",
"postgres":"openshift"}
```
- you should get the following warning in the operator logs
```bash
INFO[0007] Strategy and Provider already set, changing of cloud-resource-config config maps not allowed in existing installation. The existing Strategy is 'aws' , cloud-resource-config is now set to 'openshift'. Operator will continue to use existing Strategy  controller=controller_postgres
```
- The Postgres cr example-postgres status …
=> add conditions to not except changes in cloud-resource-config in an existing install

go.mod, pkg/providers/aws/config.go, pkg/providers/aws/credentials.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/resources/configmaps.go
Jira: https://issues.redhat.com/browse/INTLY-5467
Currently how we handled the modify of aws resources meant the status of a CR got stuck in `pending` until the next maintenance window. This change ensures a continuous happy path over applying modifications to resources.  
- Run `make cluster/prepare cluster/seed/managed/redis cluster/seed/managed/postgres`
- Once resources are created, via the aws console bump the instance size of both `elasticache` and `rds`. Ensure you select apply immediately. When AWS successfully changes the instance size and CRO reconciles on these changes it will try to modify the instances to their original size. 
- Via the AWS console you can view pending modifications. Ensure these modifications are present 
- Ensure the …
=> fix handle modify aws instance

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Jira: https://issues.redhat.com/browse/INTLY-6233 
- Run `make cluster/prepare cluster/seed/managed/postgres cluster/seed/managed/redis`
- Delete CR's when resource is created
- Ensure snapshot of redis is created
- Ensure tags are added to postgres snapshot
=> intly-6233 Final snapshots for RDS and Elasticache do not contain tags for teardown

cmd/manager/main.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Jira: https://issues.redhat.com/browse/INTLY-6232
- Run `make cluster/seed/managed/postgres cluster/seed/managed/redis`
- Run `curl localhost:8384/metrics | grep aws`
- Ensure the following metrics are there `cro_postgres_available, cro_postgres_connection, cro_postgres_info, cro_redis_available, cro_redis_connection`
- Once resources created, add `skipCreate: true` to the resources CR
- Log into AWS console, delete resources
- Remove `skipCreate: true` from CR
- Verify the resource is not recreated
- Verify the metrics are still exposed and the correct metric value
**Note :** The connection value will always be `0` if running locally
=> Intly 6232 - Ensure CRO metrics are always exposed

pkg/annotations/annotations.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/INTLY-7203
- Ensure postgres is installed correctly, note the maintenance and backup window
- Update `cloud-resources-aws-strategies` config map in the `cloud-resources-operator` namespace, Ensure the `PreferredBackupWindow` and `PreferredMaintenanceWindow` in the update differs from the current windows for the instance : 
```
data:
blobstorage: >
{"development": { "region": "eu-west-1", "createStrategy": {},
"deleteStrategy": {} }}
postgres: >
{"development": { "region": "eu-west-1", "createStrategy":
{"PreferredBackupWindow":"02:40-03:10",
"PreferredMaintenanceWindow":"mon:00:29-mon:00:59"}, "deleteStrategy": {} }}
redis: >
{"development": { …
```
=> Allow RDS backup and maintenance windows to be modified through CRO ConfigMaps

pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Jira: https://issues.redhat.com/browse/INTLY-7205
- Ensure redis is installed correctly, note the maintenance and backup window using `aws elasticache describe-cache-clusters | grep "SnapshotWindow\|PreferredMaintenanceWindow"`
- Update the cloud-resources-aws-strategies config map in the cloud-resources-operator namespace
- Ensure the `SnapshotWindow` and `PreferredMaintenanceWindow` in the update differs from the current windows for the instance 
```
data:
blobstorage: >
{"development": { "region": "eu-west-1", "createStrategy": {},
"deleteStrategy": {} }}
postgres: >
{"development": { "region": "eu-west-1", "createStrategy":
{}, "deleteStrategy": {} }}
redis: >
{"development": { …
```
=> INTLY-7205 added logic to allow updates to snapshot and maintenance windows for redis

Makefile, pkg/controller/postgressnapshot/postgressnapshot_controller.go, pkg/controller/redissnapshot/redissnapshot_controller.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/resources/custom_metrics.go
Jira: https://issues.redhat.com/browse/INTLY-6521
BYOC required
- Run ```make cluster/prepare```
- Run ```make cluster/seed/managed/postgres cluster/seed/managed/redis cluster/seed/managed/blobstorage```
- Run ```make run/local```
- Wait for the redis and postgres to reconcile 
- create snapshots from the following cr for redis and posgres 
```yaml
apiVersion: integreatly.org/v1alpha1
kind: RedisSnapshot
metadata:
name: example
namespace: cloud-resource-operator
spec: 
resourceName: example-redis
```
```yaml
apiVersion: integreatly.org/v1alpha1
kind: PostgresSnapshot
metadata:
name: example
namespace: cloud-resource-operator
spec: 
resourceName: example-postgres
```
- Run ```curl localhost:8383/metrics | grep aws```
- Ensure the following metrics are there 
- …
=> add phase status metric to aws resources

Makefile
doing some refactoring on make targets used to run locally for develo…pment
`make run` didn't specify a namespace whereas `make run/local` did
it's more useful for multiple folks developing against one cluster to use
the target where a namespace is specified.
No docs update as `make run` is being repurposed, the [local dev](https://github.com/integr8ly/cloud-resource-operator#locally) section in the
README already suggest using it.
Also removed the quotations around $NAMESPACE
- Ensure...
The output includes  `--namespace="cloud-resource-operator"`
eg.
=> Refactor make run/local to use NAMESPACE

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/config_test.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/providers/aws/sort.go
Co-authored-by: laurafitzgerald <lfitzger@example.com>
Jira: https://issues.redhat.com/browse/INTLY-8103
_Note : verification must be completed in a fresh cluster and aws account. No remnants of bundled cluster networking (cluster subnets, subnet groups, security groups) should exist in cluster vpc_
_Note : the seeded resource will not fully install, as the security group is not implemented and will cause the install to fail,  the standalone networking is provisioned before the error, the DeleteNetwork()  function is provisionally implemented, so removing the CR will clean up the standalone network. There are follow on tickets for both security group and DeleteNetwork() implementation_
- Run `make …
=> Create standalone VPC when "_network" block is defined

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
regions such as stockholm are deprecating the t2 instance type, we
should migrate to t3 instance types
verification (create):
- run 'make cluster/seed/managed/postgres'
- run 'make cluster/seed/managed/redis'
- ensure elasticache is now using 'cache.t3.micro' instances
- ensure rds is now using 'db.t3.small' instances
verification (migrate):
- from 'master', run 'make cluster/seed/managed/postgres'
- from 'master', run 'make cluster/seed/managed/redis'
- ensure elasticache is using 'cache.t2.micro' instances
- ensure rds is using 'db.t2.small' instances
- set the maintenance window for both instances to an
hour from now
- from this branch, run the operator
- ensure in aws there are now maintenance actions for upgrading
the instance type of both resources
- ensure the maintenance actions …
=> migrate aws resources to use t3 instance types by default

deploy/examples/cloud_resources_aws_strategies.yaml, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Jira: https://issues.redhat.com/browse/INTLY-8163
Pushing for review initially. Verification steps are included below but they can wait until code review are done in case of changes. 
Note: this should be run on a fresh BYOC cluster with no previous networking configuration
Note: You don't need to let the redis and postgres install completely. It's enough to ensure they get deleted correctly on deletion of the cr. (I think 🤔 )
- Checkout this branch
- Verify the standalone vpc is created by running ` aws ec2 describe-vpcs --filter "Name=tag-value,Values=RHMI Cloud Resource VPC"` - There should be one VPC - note the id of the vpc.
- Check that the redis and …
=> verify last instance of postgres or redis before deleting standalone network

README.md, pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_moq.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/providers/aws/provider_redissnapshot_test.go
Jira: https://issues.redhat.com/browse/INTLY-5160
Pushing an early pr for review to verify that the approach is good. 
- Install cloud-resource-operator with bundled resources
- git checkout v0.16.1 
- `make cluster/prepare NAMESPACE=cloud-resource-operator-<name>`
- `make cluster/seed/managed/redis NAMESPACE=clourd-resource-operator-<name>`
- `make cluster/seed/managed/redis NAMESPACE=cloud-resource-operator-<name>`
- `make run/local NAMESPACE=cloud-resource-operator-<name>`
- Get the cluster vpc id by running `aws ec2 describe-vpcs` and noting the vpc id with the tag     ```{
"Key": "kubernetes.io/cluster/<clustername>-<randomchars>",
"Value": "owned"
}```
- Wait for the resources to install. The resources of interest are below and will follow naming syntax …
=> deleting bundle network resources on deletion of last rds or elasticache

Makefile
operator-sdk v0.19.0 is throwing deprecation warnings on 
```bash
operator-sdk run --local --operator-namespace=$(NAMESPACE)
```
- Ensure... runs without the following notices
```
Flag --local has been deprecated, use 'run local' instead
Flag --operator-namespace has been deprecated, use this flag with 'run packagemanifests' instead
```
=> update makefile target run to use undeprecated flags

pkg/controller/cloudmetrics/cloudmetrics_controller.go, pkg/providers/aws/provider_postgres_metrics.go, pkg/providers/aws/provider_postgres_metrics_test.go, pkg/providers/types.go
Co-authored-by: ciaranRoche <croche@redhat.com>
Jira: https://issues.redhat.com/browse/INTLY-7226
Jira: https://issues.redhat.com/browse/INTLY-7229
Jira: https://issues.redhat.com/browse/INTLY-7230
- Run `make cluster/seed/managed/postgres` - do this twice if you like. :D 
- Run `curl localhost:8383/metrics | grep cro_postgres_`
- You should see output similar to: 
```
╭─croche@localhost ~/Projects/integreatly/cloud-resource-operator ‹intly-7226› 
╰─$ curl localhost:8383/metrics | grep cro_postgres_                                                                                                                                                                             130 ↵
% Total    % Received % Xferd  Average Speed …
```
=> exposing provider metrics in controller

pkg/controller/cloudmetrics/cloudmetrics_controller.go, pkg/moq/moq_aws/elasticache.go, pkg/providers/aws/provider_redis_metrics.go, pkg/providers/aws/provider_redis_metrics_test.go, pkg/providers/types.go
Jira: https://issues.redhat.com/browse/INTLY-7740
https://issues.redhat.com/browse/INTLY-7227
https://issues.redhat.com/browse/INTLY-7228
- Wait for Redis to provision 
- Ensure the following metrics are present using curl
```bach
curl http://localhost:8383/metrics | grep _average  
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
cro_redis_cpu_utilization_average{clusterID="mw-collab-byoc-v8926",instanceID="mwcollabbyocv8926cloudresourceopera-mnas-001",namespace="cloud-resource-operator",productName="productName",resourceID="example-red …
```
=> INTLY-7740 add redis scrape on DatabaseMemoryUsagePercentage

pkg/providers/aws/provider_postgres.go, pkg/resources/custom_metrics.go
cloud watch only provides us with free storage space, we need to expose more metrics to allow for more accurate alerting
as `predict_linear` is hard to predict on non-linear growth & results in false positives
we should follow the approach AWS take to auto scaling, and alert when free storage space is less than 10%
Co-Authored-By: laurafitzgerald <lfitzger@redhat.com>
- Run `curl localhost:8383/metrics`
- Ensure the following metrics are exposed
=> add exposing max and allocated storage metrics for postgres

pkg/providers/aws/cluster_network_provider.go
currently it is possible that duplicate azs in a region are used
to attempt to create a subnet group, under two conditions.
- aws returns a duplicate set of subnet groups
- a legacy subnet exists
ensure that duplicate azs are never used in subnet creation by
filtering out any duplicates.
verification:
- run 'make run'
- create a redis and postgres instance
- ensure both instances are created successfully in aws
=> ensure duplicate azs are never used

hack/README.md, hack/postgres/README.md, hack/postgres/clean.sh, hack/postgres/load.sh, hack/redis/README.md, hack/redis/redis-load-test.yaml, hack/redis/redis-load/Dockerfile, hack/redis/redis-load/go.mod, hack/redis/redis-load/go.sum, hack/redis/redis-load/main.go, hack/redis/redis-load/pkg/concurrency/concurrent.go, hack/redis/redis-load/pkg/string/randomString.go
Co-Authored-By: laurafitzgerald <lfitzger@redhat.com>
Related to Jira: https://issues.redhat.com/browse/INTLY-7231
- Follow `postgres/README.md` in PR to run `load.sh`
- Log into AWS, navigate to RDS console, and select created instance
- Click on Monitoring and watch the `FreeStorageSpace` graph.
- Ensure the graph trends down
- Run `make cluster/seed/managed/elasticache`
- Follow `redis/README.md` in PR to deploy `redis-load`
- Log into AWS, navigate to Elasticache console, and select created instance
- Click on primary node, and navigate to `Database Memory Usage Percentage` graph
- Ensure the graph trends up
=> add scripts to allow for easier testing of aws postgres storage alerts

pkg/controller/cloudmetrics/cloudmetrics_controller.go
Co-authored-by: darahayes <dara.hayes@redhat.com>
Jira: https://issues.redhat.com/browse/INTLY-7234
- Ensure Once Redis is deployed on aws check the metrics for this metric
```
curl localhost:8383/metrics | grep cro_redis_engine_cpu_utilization_average
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
cro_redis_engine_cpu_utilization_average{clusterID="mw-collab-byoc-z5xz6",instanceID="mwcollabbyocz5xz6redhatrhmioperator-o2wi-001",namespace="redhat-rhmi-operator",productName="productName",resourceID="example-redis",strategy="aws-elasticac …
```
=> INTLY-7234 metric for cro_redis_engine_cpu_utilization_average

deploy/examples/cloud_resources_aws_strategies.yaml
currently the example aws strategy configmap is created in dev make
targets. this means that the hardcoded region of eu-west-1 is used
even if the cluster isn't in eu-west-1 which can cause issues with
vpc setup.
remove the hardcoded region but keep the explicit keys to let users
know the possible keys that can be used in the strategy configmap.
verification:
- in cluster in a non-eu-west-1 region
- run make cluster/prepare NAMESPACE=<your-namespace>
- ensure the region isn't specified in the aws strategy configmap
- create a postgres, redis and blobstorage and ensure each are
created in the region of the cluster
it appears that custom resources (at least postgres and redis) for
aws can no longer specify a specific region. we either need to
consider this a bug or work to remove the region …
=> remove hardcoded regions from the aws strategy configmap example

openshift-ci/Dockerfile.tools, openshift-ci/README.md
/openshift-ci image. We've already bumped the version in our makefile so keeping things aligned here
Jira: https://issues.redhat.com/browse/INTLY-9952
- Run `cd openshift-ci`
- Run the commands from openshift-ci/README.md
- Ensure that the output completes and ends in `Success!!`
- See that the image is build here: https://api.ci.openshift.org/console/project/integr8ly/browse/builds/cro-base-image?tab=history and that the logs show the operator-sdk is version v0.19.0 and that the retests pass.
=> Bumping the version of the operator-sdk to v0.19.0 for the prow

go.mod, go.sum, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go, pkg/resources/version_test.go, pkg/resources/versions.go, vendor/github.com/hashicorp/go-version/LICENSE, vendor/github.com/hashicorp/go-version/README.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/github.com/hashicorp/go-version/go.mod, vendor/github.com/hashicorp/go-version/version.go, vendor/github.com/hashicorp/go-version/version_collection.go, vendor/modules.txt
Jira: https://issues.redhat.com/browse/INTLY-9686
This fixes a bug where if a Postgres or Redis instance is upgraded to a higher version number from the AWS console, then CRO would try to modify the instance back to the version specified in the aws strategy config. When the instance version is higher than what is specified in the config, then CRO tries to 'upgrade' to a lower version number which returns an error from the AWS api and puts the CR into a bad state.
The solution was either to
1. allow the request to be made to AWS and catch that specific error and do nothing
2. check the versions and only try to apply the update where appropriate
Although the 1st option would be easier I went for the second option to rule out a scenario where we're constantly making an unnecessary request to …
=> fix: don't reconcile redis/postgres versions if current version is higher than specified version

go.mod, go.sum, pkg/providers/aws/provider_postgres.go
It looks like there was a change in RDS and the `AutoAppliedAfterDate` is not always present in the payload from the `describe-pending-maintenance-actions` request anymore, so if an instance has a pending maintenance, CRO operator will panic trying to get the timestamp in a variable that wasn't returned.  
*Example of the payload sent back from the AWS CLI*
```
{
"ResourceIdentifier": "instance-id",
"PendingMaintenanceActionDetails": [
{
"Action": "db-upgrade",
"OptInStatus": "next-maintenance",
"CurrentApplyDate": "2020-10-08T02:00:00Z",
"Description": "Automatic minor version upgrade to postgres 10.13"
}
]
},
```
Jira: https://issues.redhat.com/browse/INTLY-10206
- Install the operator against a cluster that has an RDS instance and a pending maintenance available
=> fixes a change in the aws rds payload

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/provider_postgres_test.go
This PR addresses an issue in CRO where VPCs are created without being tagged, this happens because when the operator tries to add tags to the VPC, it does not check if the creation of the VPC is finalized, throwing an error `InvalidVpcID.NotFound` 
The solution for fixing this issue is to add the function `WaitUntilVpcExists` to make sure the VPC is created before adding tags to it.
Jira: https://issues.redhat.com/browse/MGDAPI-393
=> Adds a waiting function to check if the VPC exists

go.mod, go.sum, pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_moq.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/config_moq.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
adding logic to provide a default non overlapping cidr block for the standanlone network
Jira: https://issues.redhat.com/browse/MGDAPI-582
Check the config map that was created when preparing the cluster
`oc get configmaps cloud-resources-aws-strategies -n cloud-resource-operator -o json | jq '.data'`
```
{
"_network": "{\"development\": { \"region\": \"\", \"createStrategy\": { \"CidrBlock\": \"10.1.0.0/16\" }, \"deleteStrategy\": {} }}\n",
........
}
```
Create a postgres cr
Run `make cluster/seed/managed/postgres`
Verify that the standalone vpc is created using the default
`aws ec2 describe-vpcs --filter "Name=tag-value,Values=RHMI Cloud Resource VPC"`
Expected Output (with extra values stripped out)
```
{
"Vpcs": [
{ …
```
=> adding logic to provide a default non overlapping cidr block for the standanlone network

apis/integreatly/v1alpha1/types/types.go, config/crd/bases/integreatly.org_blobstorages.yaml, config/crd/bases/integreatly.org_postgres.yaml, config/crd/bases/integreatly.org_redis.yaml, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-1857
- Edit the engine version on line https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/aws/provider_postgres.go#L55 to `"10.13"`
- Edit the example-postgres cr and add applyImmediately: true to the spec
```yaml
spec:
applyImmediately: true
secretRef:
name: example-postgres-sec
tier: development
type: managed
```
- Wait for rds to finish provisioning
- Stop `make run` ctrl-c
- Edit the engine version on line https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/aws/provider_postgres.go#L55 to `"10.15"`
- `make run` again
- Confirm that the version change is applied immediately …
=> MGDAPI-1857: Add the ApplyImmediately flag to rds db engine upgrades

pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Jira: MGDAPI-2253
Add the applyImmediately flag to redis 
- Change the defaultEngineVersion to 5.0.3 on [/pkg/providers/aws/provider_redis.go](https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/aws/provider_redis.go#L45)
```go
defaultEngineVersion     = "5.0.3"
```
- Wait for redis to provision 
- Stop the Operator running locally
- Change the defaultEngineVersion back to 5.0.6
- Add the applyImmediately flag to the redis cr
```yaml
spec:
applyImmediately: true
secretRef:
name: example-redis-sec
tier: development
type: managed
```
-  Run `make run`
- The redis should upgrade the engin version to 5.0.6 and you should see that the serviceUpdate has been …
=> add the applyImmediately flag

pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
refactor to how the replicationid is checked on clusters which don't contain one
solving a nil pointer dereference
Jira:https://issues.redhat.com/browse/MGDAPI-3207
First reproduce the issue
- Check out master
- Go to aws and create a memcached elasticache via create 
- Selections -> Memcached -> Amazon Cloud -> provide a name -> number of nodes 1 -> subnet group - select one belonging to the vpc your cluster is deployed to > Use other defaults -> click create
- See that the error mentioned in the JIRA is now present.
- Clone and checkout this branch
- Stop the operator and re Run using `make run`
- The error should no longer be present
=> MGDAPI-3207

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/cluster_vpc.go, pkg/providers/aws/cluster_vpc_test.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis_test.go
Refactor to how cro finds cluster vpc and route tables to handle case where the vpc and route tables are not labled with
shared/owned cluster tags - this happens in the case of an osd byovpc cluster installation
This approach should be compatible with non byovpc cases, e.g ccs and non ccs as the tags with be in place with either owned or shared
Instead of getting the cluster VPC by the tag, get the VPC ID from the associated subnets using either the owned or shared tag.
Instead of getting the cluster Route Tables by the tag, get the RouteTables associated with the Cluster VPC ID from above.
Jira: https://issues.redhat.com/browse/MGDAPI-2906
Please make sure there are no other instances of CRO running in the clusters you are testing.
Verification steps for BYOCVPC and non-BYOCVPC are …
=> MGDAPI-2906

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/provider_postgres_test.go, pkg/resources/custom_metrics.go
Jira: [MGDAPI-3203](https://issues.redhat.com/browse/MGDAPI-3203)
Against a CCS OpenShift cluster which has no space for more VPC's:
- See metric emitted `cro_vpc_action{action='create', status='failed', error='VpcLimitExceeded'} 1`
=> MGDAPI-3203 - emit metric around vpc limits hit

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Jira: [MGDAPI-3024](https://issues.redhat.com/browse/MGDAPI-3024) 
- Run the following commands to provision redis and posgres in the `cloud-resources-operator` namespace
```bash
make cluster/prepare
make cluster/seed/managed/redis
make run
```
- We need to run both operators at the same time locally to start the second instance of the operator
- Edit the port number on to 8384 on line 61 of main.go https://github.com/integr8ly/cloud-resource-operator/blob/master/main.go#L61
- Edit the namespace env var to `cloud-resources-operator2` in the makefile https://github.com/integr8ly/cloud-resource-operator/blob/master/Makefile#L6
- In a new terminal Run the following to provision redis and postgres in `cloud-resources-operator2` namespace …
=> make isLastResource namespaced scoped so multiple cro operator can uninstall

Makefile
Jira: [MGDAPI-3294](https://issues.redhat.com/browse/MGDAPI-3294)
- Checkout latest release
- Make new release
- See no `replaces` field in manifest
</br>
- Make new release
- See `replaces` field set to `PREV_VERSION`
=> MGDAPI-3294 - add replaces into new manifests

scripts/bundle-rhmi-operators.sh
This PR fixes the [bundle-rhmi-operators.sh](https://github.com/integr8ly/cloud-resource-operator/blob/master/scripts/bundle-rhmi-operators.sh) script to support passing in `docker` as the `BUILD_TOOL` on the command line.
Jira Link: https://issues.redhat.com/browse/MGDAPI-3322
- Checkout this PR
- Update the `IMAGE_ORG` value in the [Makefile](https://github.com/integr8ly/cloud-resource-operator/blob/master/Makefile#L2) to your quay.io repo.
- Update the `VERSION` value in the [Makefile](https://github.com/integr8ly/cloud-resource-operator/blob/master/Makefile#L8) to `10.0.0`
- Update the `UPGRADE` value in the [Makefile](https://github.com/integr8ly/cloud-resource-operator/blob/master/Makefile#L10) to `false`
- Update the `PREVIOUS_OPERATOR_VERSIONS` in the …
=> MGDAPI-3322 Fixes bundle-rhmi-operators script to support docker.

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-3315
- Clone this branch, need a CCS cluster to verify
- Run 
```bash
make cluster/prepare
make run
oc get postgres example-postgres -ojson | jq .'status.phase' 
"complete"
```
- Ensure the rds instance is tagged e.g.
```bash
aws rds describe-db-instances --region us-east-2 | grep DBInstanceArn
"DBInstanceArn": "arn:aws:rds:us-east-2:<redacted>:db:rhmicloudsccsdqqdpcloudresourceoper-lbot",
aws rds list-tags-for-resource --resource-name arn:aws:rds:us-east-2:<redacted>:db:rhmicloudsccsdqqdpcloudresourceoper-lbot --region us-east-2
{
"TagList": [
{
"Key": "integreatly.org/resource-name",
"Value": "example-postgres"
},
{
"Key": "integreatly.org/product-name",
"Value": "productName"
},
{
"Key": …
```
=> MGDAPI-3376 reinstate rds tagging

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go
[Jira: <jira-id>](https://issues.redhat.com/browse/MGDAPI-3552)
- Verify that Postgres is installed with 10.16 Engine Version
=> MGDAPI-3552

.gitignore, Makefile, internal/k8sutil/k8sutil.go, pkg/providers/aws/config.go, scripts/sts/create-rhoam-policy.sh
Jira: https://issues.redhat.com/browse/MGDAPI-1725
- Provision a ROSA STS cluster
- Run `make setup/sts`
- Create rds instance
```
```
- Ensure provision of rds instance is successful
- Create redis instance 
```
make cluster/seed/managed/redis 
```
- Ensure redis instance is successful
- Delete rds and redis instance CRs
- Ensure rds and redis instance is deleted successully
=> [MGDAPI-1725] feat: allow running sts auth locally against sts cluster

go.mod, internal/k8sutil/k8sutil.go, pkg/providers/aws/config.go, pkg/providers/aws/config_test.go, pkg/providers/aws/credentials_test.go, scripts/sts/create-rhoam-policy.sh
Jira: https://issues.redhat.com/browse/MGDAPI-1725
Fixes tests failing locally due to not running in a pod, and added unit test for locally running STS 
- Run `make test/unit`
- Ensure unit tests passes
* Note: `verify_default_cidr_block_and_no_error_on_empty_cidr_block` is flaky and was pre-exisitng
=> MGDAPI-1725 - test: unit test for local sts

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-3616
This PR adds a check to the IsEnabled() function to confirm that a valid standalone VPC actually exists before returning that it does. This is required in order to fix the deletion logic for incomplete installations of the RHOAM operator where the installation got stuck because the user's VPC limit was already reached before the installation started. In this scenario, the RHOAM operator will get stuck in the Authentication stage because CRO can't create a VPC since the limit is already reached. If the user then tried to delete the RHMI CR, the uninstall would get stuck because CRO would attempt to delete a standalone VPC that doesn't exist which throws a nil pointer dereference error.
- [Provision](https://qaprodauth.cloud.redhat.com/) a …
=> MGDAPI-3616 Added check to confirm that standalone VPC exists before deleting it

pkg/providers/aws/provider_postgres.go
Jira: [MGDAPI-3656](https://issues.redhat.com/browse/MGDAPI-3656)
By setting the default value of the labels to an empty string we ensure that the service maintenance metric is created with the correct number of labels. This results in the labels `AutoAppliedAfterDate` and `CurrentApplyDate` from being present, defaulting to an empty string for all service maintenance metrics.
- Passing tests and code review should be sufficient for this change
- Without access to a cluster with pending service updates there is no information to pull from AWS to test the maintenance metric behaviour
=> MGDAPI-3656 - Set default values for service metric labels

apis/config/v1/infrastructure_types.go, pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/cluster_vpc.go, pkg/providers/aws/tags.go, pkg/providers/aws/tags_test.go
Jira: [MGDAPI-1732](https://issues.redhat.com/browse/MGDAPI-1732)
- Add to the types to extract the tags from infrastructure CR
- Merge the default CRO tags and the user-defined tags found within the CR
- In the case the same key exists in both the value from CRO takes precedence 
- Create a new CCS cluster
- Check the tags on the infrastructure CR - `oc get infrastructure cluster -o json | jq`
- Deploy a managed postgres/redis/blobstorage instance
- See the default tags from the infrastructure CR are added, along with default tags to the AWS resources
=> MGDAPI-1732 - add user-defined tags from Infrastructure CR

pkg/providers/aws/cluster_network_provider.go
Jira:[ MGDAPI-3664](https://issues.redhat.com/browse/MGDAPI-3664)
#What
Sorting CIDR ranges In order to stop flakiness of [TestNetworkProvider_ReconcileNetworkProviderConfig()](https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/aws/cluster_network_provider_test.go#L1319)
#Test
Run the test a couple of times cleaning test cache with `go clean -testcache` after each run and make sure test passes.
=> MGDAPI-3664 / sorting CIDR ranges

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_redis.go
Jira: https://issues.redhat.com/browse/MGDAPI-3909
This PR isn't changing any workflows, it's simply a performance/code readability change. It should be sufficient if all prow checks pass.
If someone wants to verify CRO is working as expected in STS mode on ROSA, they can follow the verification steps from this PR: https://github.com/integr8ly/cloud-resource-operator/pull/375
=> [MGDAPI-3909] include isSTSCluster struct property to NetworkProvider in CRO

Makefile, scripts/create-olm-bundle.sh
[MGDAPI-4119](https://issues.redhat.com/browse/MGDAPI-4119)
- Removed unused `CHANNEL` in Makefile
- Fixed `make code/gen` to use a `vendor/fix`
- Set `create-olm-bundle` to exit on first failure
- This required changes so that the `yq` commands no longer return exit code for validation
- Now that we have a initial file-based index we can now build each index from the previous, appending the new bundle - adjusted to render index
-  One of the errors we saw looked like it might be caused by using a combination of `podman` and `docker` for creation of the bundle and subsequent validation of the bundle - updated the validate command to leverage `BUILD_TOOL`
Check that we can still create an index for a new release:
- Update Makefile to point to new `VERSION` 0.40.0, `PREV_VERSION` 0.39.0, …
=> MGDAPI-4119 - ensure index creation script exits on failure

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Change the redis engine version to 6.2 and postgres engine version to 13.4
Jira: https://issues.redhat.com/browse/MGDAPI-3810, https://issues.redhat.com/browse/MGDAPI-4273
Require a CCS cluster to test
- checkout branch 
- Install and run the operator on cluster
```bash
make cluster/prepare
make run
```
- create a postgres CR
```bash
```
- wait for the install to complete and check the CR status for the version 13.3 and the message has `is as expected, aws rds status is available`
```
oc get postgres example-postgres -oyaml | yq '.status'
message: rds instance rhmicloudsccsx28fhcloudresourceoper-7yu3 is as expected, aws rds status is available
phase: complete
provider: aws-rds
secretRef:
name: example-postgres-sec
strategy: aws
version: "13.4"
```
- If …
=> MGDAPI-3810 change versions redis 6.2 postgres 13.4

pkg/providers/aws/cluster_network_provider.go
[MGDAPI-4387](https://issues.redhat.com/browse/MGDAPI-4387)
- We no longer check whether we are in STS cluster or not and create the VPC initially with tags
- Fixed a regression where we would try to reconcile tags onto STS clusters
- Provision a CCS cluster
- From 1.24.0
- Create at least 2 CR's in quick succession
- See that two VPCs are created in AWS
- Do the same from this PR
- Verify that only a single VPC is created, and tagged on creation
=> MGDAPI-4387 - tag VPC on creation for all cluster types

pkg/providers/aws/credentials_sts_manager.go, pkg/providers/aws/credentials_sts_manager_test.go, scripts/sts/sts-secret.yaml
* Update the expected sts secret format
* Remove the need for token file path as it's hardcoded in the pod template anyway
* https://github.com/integr8ly/cloud-resource-operator/blob/master/config/manager/manager.yaml#L36-L38
Jira: https://issues.redhat.com/browse/MGDAPI-4554
* Passing prow checks should do
=> MGDAPI-4554 - update expected file structure of sts secret and remove needing token file path field

Makefile, openshift-ci/Dockerfile.tools
Jira: https://issues.redhat.com/browse/MGDAPI-4625
Adds the initial support for gosec.
The hack/redis folder is being excluded as there is an issue with imports in the file. The fixing of those imports are out of scope for this work.
- Run `make gosec`
- Ensure command runs with out error.
- `echo $?` == 0
- Build the openshift-ci image.
- Ensure it builds with out error
=> MGDAPI-4625 : Add initial configuration for gosec

Makefile, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-4472
If a postgres is removed from the cluster in a case where the RDS is still in place, recreation of a postgres cr could reconnect with the RDS and CRO puts back in place the requried connection details into the cluster for applications to reconnect.
Install CRO, install a Postgres cr, Delete the namespace which removes CRO and the postgres but not the DB because the CRO controller wont have time to cleanup.
Reinstall CRO and the Postgres cr. Does it put back the connection secret etc. If not update the logic in CRO to cover this.
- Follow as in Scenario
Please see Scenario - CRO recovers Postgres CR after deletion
=> MGDAPI-4472 CRO can reconnect in the case of a postgres cr recreation

config/manager/manager.yaml, config/rbac/role.yaml, controllers/postgres/postgres_controller.go, main.go
https://issues.redhat.com/browse/MGDAPI-4844
- Install CRO via OLM by either using this index image: `quay.io/mstoklus/cloud-resource-operator:index-v0.42.0` or create your own one from this branch
- When CRO pod starts, observe at the top of the logs that there is a leader election being established
```
I1103 12:22:45.541490 1 leaderelection.go:248] attempting to acquire leader lease test/ce8de7ea.integreatly.org...
1.6674781655414956e+09 INFO Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8383"}
I1103 12:22:45.550002 1 leaderelection.go:258] successfully acquired lease test/ce8de7ea.integreatly.org
```
=> MGDAPI-4844 addition of leader election and rbacs required

pkg/providers/aws/cluster_network_provider.go, pkg/providers/aws/cluster_network_provider_test.go, pkg/providers/aws/cluster_vpc.go, pkg/providers/aws/cluster_vpc_test.go, pkg/providers/aws/provider_blobstorage.go, pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgressnapshot.go, pkg/providers/aws/provider_postgressnapshot_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redissnapshot.go, pkg/providers/aws/provider_redissnapshot_test.go, pkg/providers/aws/tags.go, pkg/providers/aws/tags_test.go, pkg/providers/gcp/cluster_network_provider.go, pkg/providers/gcp/cluster_network_provider_test.go, pkg/providers/gcp/gcpiface/redis_api.go, pkg/providers/gcp/provider_postgres.go, pkg/providers/gcp/provider_redis.go, pkg/providers/gcp/provider_redis_test.go, pkg/providers/gcp/tags.go, pkg/providers/gcp/tags_test.go, pkg/resources/tags.go, pkg/resources/tags_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-4992
- Provision a GCP cluster
- From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to the file
- Run:
```
make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp OCM_CLUSTER_REGION=europe-west2
```
- Edit the cluster.json file to update the name (and remove the expiration timestamp if necessary). You can also reduce the number of nodes to 2
- Run:
```
make ocm/cluster/create
```
- Create a Redis instance
- Checkout my pull request
```
gh pr checkout 590
```
- Log in to your cluster and run:
```
```
- Run CRO:
```
make run
```
- Create a Redis instance (v5.0): …
=> MGDAPI-4992 implement gcp redis update/upgrade logic

Makefile, apis/integreatly/v1alpha1/types/types.go, config/crd/bases/integreatly.org_blobstorages.yaml, config/crd/bases/integreatly.org_postgres.yaml, config/crd/bases/integreatly.org_redis.yaml, config/samples/integreatly_v1alpha1_redis.yaml, pkg/providers/aws/provider_redis.go, pkg/providers/aws/provider_redis_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-4929
- Verify default node size is used when not specified in CR
```
make cluster/seed/managed/redis
```
- Verify node size is used when not specified in CR but specified in strategy config map
- Update `cloud-resources-aws-strategies` config map for `redis` to 
```
oc patch configmaps cloud-resources-aws-strategies -p '{"data":{"redis":"{\"development\": { \"region\": \"\", \"createStrategy\": {\"cacheNodeType\": \"cache.t3.small\"}, \"deleteStrategy\": {}, \"serviceUpdates\": [\"elasticache-20210615-002\"]  }}\n"}}' --type merge
```
- Create second redis
```
make cluster/seed/managed/redis REDIS_NAME=example-redis2
```
- Verify node size is used when specified in the CR
``` …
```
=> MGDAPI-4929 - feat: allow defining cache node size in Redis CR

pkg/providers/aws/provider_postgres.go, pkg/providers/aws/provider_postgres_test.go, pkg/providers/aws/provider_redis.go, pkg/providers/gcp/provider_postgres.go, pkg/providers/gcp/provider_postgres_test.go, pkg/providers/gcp/provider_redis.go, pkg/resources/labels.go, pkg/resources/labels_test.go
Jira: https://issues.redhat.com/browse/MGDAPI-5009
- Provision a GCP cluster
- From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to the file
- Run:
```
make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp OCM_CLUSTER_REGION=europe-west2
```
- Edit the cluster.json file to update the name (and remove the expiration timestamp if necessary). You can also reduce the number of nodes to 2
- Run:
```
make ocm/cluster/create
```
- Create a Postgres instance
- Checkout my pull request
```
gh pr checkout 605
```
- Log in to your cluster and run:
```
```
- Install the operator from my index image:
```
cat << EOF …
```
=> MGDAPI-5009 implement gcp postgres metrics

pkg/providers/aws/provider_postgres.go
Jira: https://issues.redhat.com/browse/MGDAPI-5092
- e2e tests shuld be sufficient for this.
=> MGDAPI-5092 bump rds version

pkg/providers/openshift/provider_postgres.go
Jira: [MGDAPI-5153](https://issues.redhat.com/browse/MGDAPI-5153)
- Prepare the cluster for CRO: `make cluster/prepare`
- Run the operator locally: `make run`
- Create the Postgre CR: `make cluster/seed/workshop/postgres`
- Wait for Postgres CR to reconcile
- Verify that the version of `psql` inside the postgres pod is `13.7`: 
```
oc rsh $(oc get pods -n cloud-resource-operator --no-headers | awk '{print $1}') psql -V
```
=> MGDAPI-5153 Update default workshop PostgreSQL version from 10.x to 13.x

pkg/providers/gcp/provider_postgres.go, pkg/providers/gcp/provider_postgres_test.go, pkg/providers/gcp/provider_redis.go, pkg/providers/gcp/provider_redis_test.go
Jira: [MGDAPI-5303](https://issues.redhat.com/browse/MGDAPI-5303)
Adding logic to add the resourceIdentifier annotation to postgres and redis CRs if they have not been successfully added on creation of these resources.
- Provision a GCP cluster
- From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to this file.
- Run make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp
- Edit the cluster.json file to update the name (and remove the expiration timestamp if necessary) You can also reduce the number of nodes to 3.
- Run `make ocm/cluster/create`
- Create a Postgres instance
- Checkout this pull request `gh pr checkout 667`
- Log in to your …
=> MGDAPI-5303 Annotation missing from CRO CR's on GCP

controllers/cloudmetrics/cloudmetrics_controller.go
[MGDAPI-5082](https://issues.redhat.com/browse/MGDAPI-5082)
Discovered an issue in v1.0.0 - metrics were added during the cloudmetrics_controller initialisation here for GCP [`553f8d9` (#671)](https://github.com/integr8ly/cloud-resource-operator/pull/671/commits/553f8d9bcbf6747f8b6a68ec0cb6290fc95d9600#diff-25b42e67d7d5bf1384b1a2dbdbe0fb4d0c3ecb16681879be4637aed3d7d95270R106-R134) but the result was that the original metrics created by AWS were registered twice. Once the Postgres instance is created, the metric is re-registered when setting for the first time [here](https://github.com/integr8ly/integreatly-operator/blob/master/vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go#L90-L91) but without the help message. This results in a conflict and the pod …
=> MGDAPI-5082 - fix issue with metrics creation

apis/integreatly/v1alpha1/types/types.go, pkg/providers/gcp/cluster_network_provider.go, pkg/providers/gcp/cluster_network_provider_moq.go, pkg/providers/gcp/cluster_network_provider_test.go, pkg/providers/gcp/provider_postgres.go, pkg/providers/gcp/provider_redis.go, pkg/providers/gcp/provider_redis_test.go
Jira: issues.redhat.com/browse/MGDAPI-5458
- Run `make run` against a GCP cluster
- Seed Postgres
```
PROVIDER=gcp make cluster/seed/postgres
```
* Verify phase is in progress during ip address range or connection service creation
```
oc get postgres example-postgres -n cloud-resource-operator -o json | jq '.status'
```
* Delete postgres
- Seed Redis
```
PROVIDER=gcp make cluster/seed/redis
```
- Verify phase is in progress during ip address range or connection service creation
```
oc get redis example-redis -n cloud-resource-operator -o json | jq '.status'
```
* Delete redis
=> MGDAPI-5458 - refactor: remove blocking gcp calls

pkg/providers/gcp/provider_postgres.go, pkg/providers/gcp/provider_postgres_test.go, pkg/providers/gcp/provider_redis.go, pkg/providers/gcp/provider_redis_test.go
https://issues.redhat.com/browse/MGDAPI-5459
- GCP cluster
- `PROVIDER=gcp make cluster/seed/postgres`
- `PROVIDER=gcp make cluster/seed/redis`
- Wait for both instances to provision 
- Shut down CRO
- Remove one of the labels in postgres and update "deletion protection" to false
- In redis, scale the storage from 1gb to 5gb
- Recover CRO
- Confirm that settings got rolled back to what they were.
=> MGDAPI-5459 remove maintenance window

pkg/providers/gcp/provider_redis.go
[MGDAPI-5649](https://issues.redhat.com/browse/MGDAPI-5649)
From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to this file. Adjust this command to suit your needs, it will generate a config at ocm/cluster.json:
```sh
OCM_CLUSTER_NAME=acatterm-ccs OCM_CLUSTER_LIFESPAN=24 COMPUTE_NODES_COUNT=2 BYOC=true CLOUD_PROVIDER=gcp make -f make/ocm.mk ocm/cluster.json
```
Once you have checked the ocm/cluster.json, create the cluster:
```sh
make -f make/ocm.mk ocm/cluster/create
```
Run the operator from master:
```
oc patch configmap cloud-resources-gcp-strategies -n cloud-resource-operator --type=json -p='[{"op": "replace", …
```
=> MGDAPI-5649 - fix redis update on each reconcile

Makefile, pkg/providers/gcp/provider_redis.go, pkg/providers/gcp/provider_redis_test.go
[MGDAPI-5691](https://issues.redhat.com/browse/MGDAPI-5691)
From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to this file. Adjust this command to suit your needs, it will generate a config at ocm/cluster.json:
```sh
OCM_CLUSTER_NAME=acatterm-ccs OCM_CLUSTER_LIFESPAN=24 COMPUTE_NODES_COUNT=2 BYOC=true CLOUD_PROVIDER=gcp make -f make/ocm.mk ocm/cluster.json
```
Once you have checked the ocm/cluster.json, create the cluster:
```sh
make -f make/ocm.mk ocm/cluster/create
```
Run the operator from this branch:
```
make run
```
Create a new Redis CR with a custom size:
```
REDIS_NODE_SIZE=7 PROVIDER=gcp make …
```
=> MGDAPI-5691 - allow specifying redis size for GCP

pkg/providers/gcp/gcpiface/storage_api.go, pkg/providers/gcp/provider_postgressnapshot.go, pkg/providers/gcp/provider_postgressnapshot_test.go
[MGDAPI-5705](https://issues.redhat.com/browse/MGDAPI-5705)
From the master branch of the [Delorean](https://github.com/integr8ly/delorean) repo create a file in the root of the repo called gcp_service_account.json. Request GCP credentials and add these to this file. Adjust this command to suit your needs, it will generate a config at ocm/cluster.json:
```sh
OCM_CLUSTER_NAME=acatterm-ccs OCM_CLUSTER_LIFESPAN=24 COMPUTE_NODES_COUNT=2 BYOC=true CLOUD_PROVIDER=gcp make -f make/ocm.mk ocm/cluster.json
```
Once you have checked the ocm/cluster.json, create the cluster:
```sh
make -f make/ocm.mk ocm/cluster/create
```
Run the operator from this branch:
```
make run
```
Create a new Postgres CR:
```
PROVIDER=gcp make cluster/seed/postgres
```
Set the snapshot …
=> MGDAPI-5705 - set object lifecycle for buckets

pkg/providers/aws/provider_redis.go
Jira: [MGDAPI-5609](https://issues.redhat.com/browse/MGDAPI-5609)
Move specifiedUpdate in CRO for redis outside of the serviceMaintenance bloc
Eye review of code changes should be sufficient
=> MGDAPI-5609 - move serviceUpdates outside of maintenanceWindow

pkg/providers/openshift/provider_redis.go, test/e2e/redis_test.go
JIRA: [MGDAPI-6133](https://issues.redhat.com/browse/MGDAPI-6133)
1. Provision non-CCS cluster
2. Build CRO images from this PR
3. Install RHOAM from CatalogSource but before creating the RHMI CR, patch the managed-api-service CSV with the custom CRO image
4. Verify that the RHOAM installation completes
=> MGDAPI-6133 Bump default Redis to 6

pkg/providers/aws/provider_postgres.go
Jira:  https://issues.redhat.com/browse/MGDAPI-6214
- Ensure...
=> MGDAPI-6214 - bump aws rds version

go.mod, go.sum, vendor/github.com/hashicorp/go-version/CHANGELOG.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/modules.txt
address dependabot PR:  https://github.com/integr8ly/cloud-resource-operator/pull/442 
Jira: https://issues.redhat.com/browse/MGDAPI-6233
- Ensure...
=> MGDAPI-6233 - Bump github.com/hashicorp/go-version from 1.5.0 to 1.6.0

pkg/providers/openshift/provider_redis.go
Jira: MGDAPI-6317
- Run `make cluster/seed/redis`
- wait for the redis pod to be ready and check the version
```bash
oc logs $(oc get po | awk '{print $1}'| sed -n '2 p') 
1:C 21 May 2024 14:26:31.604 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 May 2024 14:26:31.604 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 May 2024 14:26:31.604 # Configuration loaded
1:M 21 May 2024 14:26:31.604 * monotonic clock: POSIX clock_gettime
1:M 21 May 2024 14:26:31.605 * Running mode=standalone, port=6379.
1:M 21 May 2024 14:26:31.605 # Server initialized
1:M 21 May 2024 14:26:31.605 * Ready to accept connections
```
=> MGDAPI-6317 change the provider openshift redis to version 7

openshift-ci/Dockerfile.tools
Jira: https://issues.redhat.com/browse/MGDAPI-6290
- Ensure...
=> MGDAPI-6290-3 set openshift-ci to go1.20

pkg/providers/aws/provider_redis.go
Jira: MGDAPI-6292
- Use a ccs cluster
- Run `PROVIDER=aws make cluster/seed/redis`
- Ensure that the version in the status is 7.1
```yaml
status:
message: 'successfully created and tagged, aws elasticache status is available'
phase: complete
provider: aws-elasticache
secretRef:
name: example-redis-sec
strategy: aws
version: 7.1.0
```
- Delete the redis CR
- checkout master
- Run `PROVIDER=aws make cluster/seed/redis`
- Wait for status `phase: completed` in the cr
- modify the maintenance window in the aws to the current time ( or do it in the ui)
```bash
~ aws elasticache describe-replication-groups | jq -r '.ReplicationGroups[].ReplicationGroupId'  
<your-replication-group-id>
~ aws elasticache …
```
=> MGDAPI-6292 bump the redis engine version to 7.1

Dockerfile
Jira: [MGDAPI-6421](https://issues.redhat.com/browse/MGDAPI-6421)
Adding `USER root` is required to avoid permission issues if building via podman v4
Have a podman v4 (I validated with v4.9.4 because our ci-cd pipeline uses that version) installed. Then execute
`make image/build/pipelines`
Alternatively, you can trigger ci-cd pipeline I created to validate this:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Playground/job/trepel/job/cro-release/
Or simply just review its successful build:
https://master-jenkins-csb-intly.apps.ocp-c1.prod.psi.redhat.com/job/Playground/job/trepel/job/cro-release/13/
- see Parameters -> that this PR was used
- see Console Output -> that the `podman bulid...` passed there successfully
=> MGDAPI-6421 Use root to support CRO base image build via podman v4

pkg/providers/aws/provider_postgres.go
Jira: [MGDAPI-6539](https://issues.redhat.com/browse/MGDAPI-6539)
- CCS cluster required
- Run `PROVIDER=aws make cluster/seed/postgres`
- Confirm the postgres cr finishes creation and the engine version is 13.18
```bash
oc get postgres example-postgres -oyaml | yq '.status'
message: rds instance aucunninccsqnpxccloudresourceoperat-snit is as expected, aws rds status is available
phase: complete
provider: aws-rds
secretRef:
name: example-postgres-sec
strategy: aws
version: "13.18"
```
=> MGDAPI-6539 bump postgres 13.18

openshift-ci/Dockerfile.tools
Jira: MGDAPI-6668 
visual inspection only prow jobs won't pass
=> MGDAPI-6668 bump prow to go1.23

config/manager/manager.yaml
Jira: MGDAPI-1142
- checkout this branch
- update the IMAGE_ORG in the makefile to point at your quay repo
```bash
IMAGE_REG ?= quay.io
IMAGE_ORG ?= <your_quay_username>
IMAGE_NAME ?= cloud-resource-operator
```
- build an image and push it
```bash
make image/build
make image/push
```
- you can then deploy the image
```bash
make cluster/prepare
OPERATOR_IMAGE=<your-image> make cluster/deploy
```
- this will create an CRO operator deployment
- check the operator deployment yaml for the request and limits 
```bash
oc -n cloud-resource-operator get deployment cloud-resource-operator -o jsonpath='{.spec.template.spec.containers[0].resources}'
```
=> MGDAPI-1142 add request and limits to the operator deployment
